// Code generated by MockGen. DO NOT EDIT.
// Source: accessors.go
//
// Generated by this command:
//
//	mockgen -source accessors.go -package mocks -destination mocks/mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockproviderAccessor is a mock of providerAccessor interface.
type MockproviderAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockproviderAccessorMockRecorder
	isgomock struct{}
}

// MockproviderAccessorMockRecorder is the mock recorder for MockproviderAccessor.
type MockproviderAccessorMockRecorder struct {
	mock *MockproviderAccessor
}

// NewMockproviderAccessor creates a new mock instance.
func NewMockproviderAccessor(ctrl *gomock.Controller) *MockproviderAccessor {
	mock := &MockproviderAccessor{ctrl: ctrl}
	mock.recorder = &MockproviderAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproviderAccessor) EXPECT() *MockproviderAccessorMockRecorder {
	return m.recorder
}

// Ask mocks base method.
func (m *MockproviderAccessor) Ask(ctx context.Context, prompt string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ask", ctx, prompt)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ask indicates an expected call of Ask.
func (mr *MockproviderAccessorMockRecorder) Ask(ctx, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ask", reflect.TypeOf((*MockproviderAccessor)(nil).Ask), ctx, prompt)
}

// IsAvailable mocks base method.
func (m *MockproviderAccessor) IsAvailable() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAvailable")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAvailable indicates an expected call of IsAvailable.
func (mr *MockproviderAccessorMockRecorder) IsAvailable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAvailable", reflect.TypeOf((*MockproviderAccessor)(nil).IsAvailable))
}

// Name mocks base method.
func (m *MockproviderAccessor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockproviderAccessorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockproviderAccessor)(nil).Name))
}

// MockmoduleAccessor is a mock of moduleAccessor interface.
type MockmoduleAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockmoduleAccessorMockRecorder
	isgomock struct{}
}

// MockmoduleAccessorMockRecorder is the mock recorder for MockmoduleAccessor.
type MockmoduleAccessorMockRecorder struct {
	mock *MockmoduleAccessor
}

// NewMockmoduleAccessor creates a new mock instance.
func NewMockmoduleAccessor(ctrl *gomock.Controller) *MockmoduleAccessor {
	mock := &MockmoduleAccessor{ctrl: ctrl}
	mock.recorder = &MockmoduleAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmoduleAccessor) EXPECT() *MockmoduleAccessorMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockmoduleAccessor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockmoduleAccessorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockmoduleAccessor)(nil).Name))
}

// TransformCommitMessage mocks base method.
func (m *MockmoduleAccessor) TransformCommitMessage(ctx context.Context, message string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransformCommitMessage", ctx, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TransformCommitMessage indicates an expected call of TransformCommitMessage.
func (mr *MockmoduleAccessorMockRecorder) TransformCommitMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransformCommitMessage", reflect.TypeOf((*MockmoduleAccessor)(nil).TransformCommitMessage), ctx, message)
}

// TransformPrompt mocks base method.
func (m *MockmoduleAccessor) TransformPrompt(ctx context.Context, prompt string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransformPrompt", ctx, prompt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TransformPrompt indicates an expected call of TransformPrompt.
func (mr *MockmoduleAccessorMockRecorder) TransformPrompt(ctx, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransformPrompt", reflect.TypeOf((*MockmoduleAccessor)(nil).TransformPrompt), ctx, prompt)
}
